#version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_HOST: ${HOST}
      POSTGRES_PORT: ${PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER} -d ${NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    env_file:
      - ./.env

  celery:
    build: .
    command: >
       bash -c "celery -A config worker --loglevel=info --pool=solo"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: >
      bash -c "celery -A config beat -l info"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - celery

volumes:
  postgres_data:
  static_volume:
  redis_data: